# -*- coding: utf-8 -*-
"""Dashboard de Retención de Clientes - Q1 2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tAthuAE8SvlRggTVJOdpn1FAM0oGMLzy
"""

import pandas as pd
import numpy as np

df = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

# Convertir TotalCharges a numérico, los errores se vuelven NaN (nulos)
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

# Revisar cuántos nulos quedaron
print(f"Valores nulos en TotalCharges: {df['TotalCharges'].isnull().sum()}")

# Como son pocos (aprox. 11), los eliminamos para no sesgar el análisis
df.dropna(inplace=True)

# La columna customerID no sirve para el análisis estadístico, la quitamos
df.drop('customerID', axis=1, inplace=True)

# Cambiar la variable objetivo 'Churn' a números: Yes = 1, No = 0
df['Churn'] = df['Churn'].map({'Yes': 1, 'No': 0})

print(df.info())
print(df.head())

"""**Análisis Visual**"""

import matplotlib.pyplot as plt
import seaborn as sns

# Configuración visual
sns.set(style="whitegrid")

# ¿Qué tipo de contrato tiene más fuga?
plt.figure(figsize=(10, 6))
sns.countplot(x='Contract', hue='Churn', data=df)
plt.title('Fuga de Clientes por Tipo de Contrato')
plt.show()

"""**Feature Engineering (Creación de Valor)**"""

# 1. Agrupar la antigüedad (Tenure) en cohortes para ver dónde está el riesgo
def group_tenure(t):
    if t <= 12: return '0-12 meses'
    elif t <= 24: return '1-2 años'
    elif t <= 48: return '2-4 años'
    else: return '4+ años'

df['TenureGroup'] = df['tenure'].apply(group_tenure)

# 2. Variable de "Servicios Totales" contratados
# Esto mide la "lealtad": a más servicios, más difícil es que el cliente se vaya
services = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']
df['TotalServices'] = (df[services] == 'Yes').sum(axis=1)

# Ver la relación entre servicios y fuga
print(df.groupby('TotalServices')['Churn'].mean())

"""**Preparación para Visualización (Power BI o Tableau)**"""

# Guardar el dataset limpio y procesado para usarlo en Power BI
df.to_csv('Telco_Churn_Clean.csv', index=False)

# Ver qué variables influyen más en el Churn (numéricamente)
# Solo columnas numéricas
corr = df.select_dtypes(include=[np.number]).corr()

plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Matriz de Correlación: ¿Qué empuja al cliente a irse?')
plt.show()